# Generated by Django 4.0.2 on 2022-02-25 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalEntry', '0002_journalentry_author_alter_journalentry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 20, 29, 55, 225617)),
        ),
    ]
