# Generated by Django 4.0.2 on 2022-03-11 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalEntry', '0003_journalentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 16, 15, 58, 777166)),
        ),
    ]
