# Generated by Django 4.0.2 on 2022-02-25 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalEntry', '0003_journalentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 21, 16, 20, 530003)),
        ),
    ]
