# Generated by Django 4.0.2 on 2022-03-11 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalEntry', '0004_journalentry_category_alter_journalentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 16, 17, 5, 922024)),
        ),
    ]
