# Generated by Django 4.0.2 on 2022-03-13 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JournalEntry', '0005_alter_journalentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
