# Generated by Django 4.0.2 on 2022-03-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JournalEntry', '0007_journalentry_related_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='title',
        ),
    ]
