# Generated by Django 4.0.2 on 2022-03-24 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JournalEntry', '0008_remove_journalentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
