# Generated by Django 4.0.2 on 2022-04-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JournalEntry', '0009_alter_journalentry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='subtopic_area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='topic_area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
