# Generated by Django 4.0.2 on 2022-05-16 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('is_on_success_list', models.BooleanField()),
                ('is_urgent', models.BooleanField()),
                ('is_important', models.BooleanField()),
                ('ideal_complete_before_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_completion_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
