# Generated by Django 4.0.2 on 2022-05-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_task_actual_completion_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_completion_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ideal_complete_before_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
