# Generated by Django 4.0.2 on 2022-03-11 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 16, 17, 5, 888801)),
        ),
    ]
