# Generated by Django 4.0.2 on 2022-03-13 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0002_goal_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='days_until_due',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='focus',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='goal',
            name='how_to_measure_success',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='statement',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='goal',
            name='content',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='goal',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
