# Generated by Django 4.0.2 on 2022-03-13 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_name_user_username'),
        ('Goals', '0003_goal_days_until_due_goal_focus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='User.user'),
        ),
    ]
